// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/zechao158/ecomm/types"
	"sync"
)

// Ensure, that MockProductRepository does implement types.ProductRepository.
// If this is not the case, regenerate this file with moq.
var _ types.ProductRepository = &MockProductRepository{}

// MockProductRepository is a mock implementation of types.ProductRepository.
//
//	func TestSomethingThatUsesProductRepository(t *testing.T) {
//
//		// make and configure a mocked types.ProductRepository
//		mockedProductRepository := &MockProductRepository{
//			GetProductsFunc: func(contextMoqParam context.Context) ([]types.Product, error) {
//				panic("mock out the GetProducts method")
//			},
//		}
//
//		// use mockedProductRepository in code that requires types.ProductRepository
//		// and then make assertions.
//
//	}
type MockProductRepository struct {
	// GetProductsFunc mocks the GetProducts method.
	GetProductsFunc func(contextMoqParam context.Context) ([]types.Product, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetProducts holds details about calls to the GetProducts method.
		GetProducts []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
	}
	lockGetProducts sync.RWMutex
}

// GetProducts calls GetProductsFunc.
func (mock *MockProductRepository) GetProducts(contextMoqParam context.Context) ([]types.Product, error) {
	if mock.GetProductsFunc == nil {
		panic("MockProductRepository.GetProductsFunc: method is nil but ProductRepository.GetProducts was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockGetProducts.Lock()
	mock.calls.GetProducts = append(mock.calls.GetProducts, callInfo)
	mock.lockGetProducts.Unlock()
	return mock.GetProductsFunc(contextMoqParam)
}

// GetProductsCalls gets all the calls that were made to GetProducts.
// Check the length with:
//
//	len(mockedProductRepository.GetProductsCalls())
func (mock *MockProductRepository) GetProductsCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockGetProducts.RLock()
	calls = mock.calls.GetProducts
	mock.lockGetProducts.RUnlock()
	return calls
}
